import Header from "../../components/Header";
import "./globals.css";


export const metadata = {
  title: "DzK",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.png",
  }
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header />
        {children}
      </body>
    </html>
  );
}
